### PR TITLE
Fix IndexOutOfBounds

### PR DESCRIPTION
**Pull request by Sanduhr32**
#### Pull Request Checklist
Please follow the following steps before opening this PR.<br>
PRs that do not complete the checklist will be subject to denial for
missing information.

- [x] I have checked the [pull request page][pull-request] for upcoming
      or merged features/bug fixes.
- [x] I have read JDA's [contributing guidelines][contributing].

#### Pull Request Information
Check and fill in the blanks for all that apply:

- [x] My PR fixes a bug, error, or other issue with the library's codebase.
- [x] My PR is for the `command` module of the JDA-Utilities library.

#### Description
fixes an index out of bounds when trying to make message parts, when the raw message is a bot mention only.
Edit:
line 903 or 917 would fail either way if the index is beyond rawLength
1. substring(start, end) https://github.com/openjdk/jdk17/blob/master/src/java.base/share/classes/java/lang/String.java#L2704 (calls point 2)
2. ("checkIndices") https://github.com/openjdk/jdk17/blob/master/src/java.base/share/classes/java/lang/String.java#L4599-L4604

### CODE REVIEW

**Review by GameKuchen — APPROVED** [review]

**Comment by Chew** [comment]
I could swear this was fixed or was reported or something. That's why I haven't replied yet since I don't remember 😂

**Comment by Chew** [comment]
Ah it's just #60 / #61

**Comment by Sanduhr32** [comment]
/shrug that seemed todo a lot that isn't required.

**Comment by Chew** [comment]
This seems more like a band-aid fix, I want to test some other methods to see what the root issue is. Will investigate.

**Comment by Sanduhr32** [comment]
It overscans the full message string, if it's just the mention as the commands prefix

**Comment by GameKuchen** [comment]
I'm still having issues with this error getting dropped? Any news on this?

**Pull request closed without merging**
