### PR TITLE
Added commandPreProcessBiFunction with Command argument

### PR DESCRIPTION
**Pull request by lilmayu**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing
[pull-request]: https://github.com/JDA-Applications/JDA-Utilities/pulls

#### Pull Request Checklist
Please follow the following steps before opening this PR.<br>
PRs that do not complete the checklist will be subject to denial for
missing information.

- [x] I have checked the [pull request page][pull-request] for upcoming
      or merged features/bug fixes.
- [x] I have read JDA's [contributing guidelines][contributing].

#### Pull Request Information
Check and fill in the blanks for all that apply:

- [ ] My PR fixes a bug, error, or other issue with the library's codebase.
- [x] My PR is for the `Command` module of the JDA-Utilities library.
- [ ] My PR creates a new module for the JDA-Utilities library: `______`.

#### Description

Changed `commandPreProcessFunction` type to BiFunction to utilize resolved Command. Can be useful, if you want to cancel on a per-command basis.

### CODE REVIEW

**Comment by Andre601** [comment]
Will this break existing setups?

**Comment by lilmayu** [comment]
> Will this break existing setups?

Unfortunately yes, but fixing it is easy - `event -> {}` to `(event, command) -> {}` (any existing command in lamba will work as before, because MessageReceivedEvent is still there). If it would be that big of a problem, there can be extra variable, but I think that would be rather messy.

**Comment by Chew** [comment]
It is breaking so I'm a little hesitant. I've been wanting to do a 2.0 release that also changes how the `.reply()` function works.

Does this let you cancel individual command execution? That would be pretty nifty.

**Comment by lilmayu** [comment]
> It is breaking so I'm a little hesitant. I've been wanting to do a 2.0 release that also changes how the `.reply()` function works.
> 
> Does this let you cancel individual command execution? That would be pretty nifty.

Yes, you can. For example:
```
.setCommandPreProcessFunction((event, command) -> {
    if (command.getName().equalsIgnoreCase("some_command_name")) {
        // Cancels only command with name 'some_command_name'
        return false;
    }

    // Allows any other command
    return true;
});
```
You could do this theoretically even with MessageReceivedEvent, but you had to remove a prefix, parse it and do other stuff to check for sub-commands, etc. But it would get messy real quick, plus - why? JDA-Utilities already resolved command, so it would be just extra code to get something that is already done somewhere else.

And another advantage -> If you have for example custom implementation of Command, let's say CustomCommand, and you would implement something for just yourself (I don't know, custom command type, anything), you can check if that Command is an instance of CustomCommand -> cast Command into CustomCommand and you can use your custom implementation.

**Comment by lilmayu** [comment]
Just remembered this PR. I will make and push here the same pre-process thingy for slash commands as well if it is not already implemented.

**Comment by Chew** [comment]
Hello! I didn't forget this don't worry.

I'm hesitant to merge this since it'd be a breaking change, but also hesitant to add yet another option to the massive constructor, but that may be the best case (which would include deprecating the old method to prefer the new one).

If a 2.0 or another breaking change occurs, we can shift to removing the old version.

**Comment by Chew** [comment]
So I do wanna get this in for 2.0, but I wanna keep both (with the old way deprecated) for 1.24.0, then we can come back and remove it for 2.0

**Review by Chew — APPROVED** [review]
Went ahead made my changes, will give you credit though. Thank you!

Be sure to switch to the new one since the old AND new won't both work.

**Pull request merged**
