### PR TITLE
update gradle.

### PR DESCRIPTION
**Pull request by portlek**
#### Pull Request Checklist

- [x] I have checked the [pull request page][pull-request] for upcoming
      or merged features/bug fixes.
- [x] I have read JDA's [contributing guidelines][contributing].

#### Pull Request Information

- [ ] My PR fixes a bug, error, or other issue with the library's codebase.
- [ ] My PR is for the `______` module of the JDA-Utilities library.
- [ ] My PR creates a new module for the JDA-Utilities library: `______`.

#### Description

Updates the gradle version.

### CODE REVIEW

**Review by Chew — CHANGES_REQUESTED** [review]
`gradle wrapper --gradle-version 7.3.3`

**Comment by portlek** [comment]
@Chew i did but there is no any change after the run.

**Comment by Chew** [comment]
Weird, I had changes 🤔 will look later

**Comment by portlek** [comment]
@Chew i guess you can change on my pull request too, so if you have the changes just commit it.

**Comment by Chew** [comment]
7.4 is here :)

**Comment by portlek** [comment]
@Chew done.

**Pull request closed without merging**
