### PR TITLE
Add missing Collection overload

### PR DESCRIPTION
**Pull request by Andre601**
(This PR-Template is shit)

Added the missing `addItems(Collection<MessageEmbed>)` and `setItems(Collection<MessageEmbed>)` from my original PR.

### CODE REVIEW

**Comment by Chew** [comment]
1.20.1

**Comment by Andre601** [comment]
> 1.20.1

For whatever reasons is that not included in this version.
I downloaded 1.20.1 but the overloads aren't there... You sure it pushed the proper update or are you waiting?
image

**Comment by Chew** [comment]
I didn't pull first.. :(
1.20.1 for real now (I also forgot to bump the release but it dutifully overwrote 1.20.1 anyway)

**Comment by Andre601** [comment]
Still no luck (Maybe it takes time to validate the release or something? Is it Maven-like?)

Just push to 1.20.2 imo to fix this

**Comment by Chew** [comment]
Alright, pushed that too (maven whyyy)

**Comment by Andre601** [comment]
Now it finally works

**Pull request merged**
